# Generated by Django 5.2.4 on 2025-07-10 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_rename_member_parent_user_rename_member_spouse_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='spouse',
            name='spouse',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spouse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=200, unique_for_month='meeting_date')),
                ('meeting_date', models.DateField()),
                ('adopted', models.BooleanField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adopter1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes_adopted', to=settings.AUTH_USER_MODEL)),
                ('adopter2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes_adopted2', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Minutes',
        ),
    ]
