# Generated by Django 5.2.4 on 2025-07-10 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_spouse_spouse_minute_delete_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spouse',
            name='spouse',
        ),
        migrations.RemoveField(
            model_name='spouse',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='community.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='community.profile'),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Spouse',
        ),
    ]
