# Generated by Django 5.2.4 on 2025-07-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_member_webhookendpoint_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
    ]
